-- Insert article for 'We have a Samaritan'
INSERT INTO articles (id, title, author, job_title, works_at, category, image_url, alt_text, content, excerpt, publish_date, read_time, is_featured, language) VALUES
('we-have-a-samaritan', 'We have a Samaritan', 'Dr. Anil Kurichimuttom', 'Doctor', 'Christian Ministry', 'Faith', 'assets/images/articles/we-have-a-samaritan.jpg', 'Illustration of the Good Samaritan helping the wounded man', 'Again, we are at the threshold of a new year. It is an opportunity for us to look back into the days we shared our time, energy and other resourses. A question often surprises me: What happens around us? Sometimes I feel that people fades away and nature persists, a repetition of life cycle. It is necessary to consider each situation wisely, and we should have a thorough understanding of everything. Life''s realities differ from time to time, but the promises of God always remain Yes and Amen.

We Pentecostals always prefer messages that motivate them. There are two questions based on people''s expectations: What do listeners expect to hear? and What does a preacher like to convey? I prefer the latter. The argument related to the first question is relevant now because listeners have a tendency to impose expectations on the preacher. It is an improper approach from people and they should remain theologically sound. Jesus is not a magician who always satisfies our needs. He wants us to be solid in every situation.

I have a beautiful message for the new year, and it is based on Biblical details of ''Good Samaritan'' which is thought-provoking and inspirational. We get overwhelmed and motivated to mention the events leading to the arrival of a stranger who is the most influential character in the Bible. The short passage containing only ten verses (Lk. 10:25-35) is far reaching than any other literature. I feel tragedies of Shakespeare and world class epics are inferior to this Biblical passage. The relevance does matter. Jesus here responds to a lawyer''s question ''Who is my neighbour?'' The major character of this story is a man who is wounded, departed, and left half dead. There comes a priest and a levite, and it is a time of possibility and expectation. A significant phrase in connection with them is ''... he passed by on the other side''. They represent the religion or system which is mechanical in nature. I don''t know whether Jesus favours the systemic order of religion where the poor men and women are sidelined. Jesus'' ministry is not intentional and it remains active and requires quick response. The position of leader happens to be aspiritual in such systems where knowingly or unknowingly politics controls everyone from top to bottom.

Humanity and its sacredness is supreme to rituals and practices. If you stick on to the system, you cannot become a samaritan who behaves normal and is present active in urgent times. Samaritan has got several qualities: He is compassionate who binds up wounds, pours in oil and wine, sets the wounded on his own beast, and brings him to an inn, and takes care of him. Then, what is the role of priests. They are appointed for conducting all rituals on the altar. They are confined to services, and they keep a particular style, vocabulary, and way of presentation. It is a fact that spiritual leaders are not the handiworks of any organization, but God''s creation. Then who is a Levite? Levites were called to protect the tabernacle and its sacred contents. They also lead praise and worship, singing hymns, and playing instruments. Contrary to Priests and Levites, Samaritans are ethnocentric group sharing the Pentateuch (the first five books of the Hebrew Bible) as a central scripture, but differs by rejecting the rest of the Hebrew Bible and rabbinic traditions. The Samaritans believe their holy site is Mount Gerizim, not Jerusalem. A Samaritan who comes to help the wounded is not a mere traveller. While travelling to his destination, he has eye for both sides and on the road. So he could see this man and saved him.

The wounded man represents the entire mankind who seek salvation from Jesus, the very Samaritan. Jesus was a jew came to save us from sin. Though he was a stranger to us, he was willingly happy to leave heaven, and took us from the sin. Later, he entrusted us into the hands of Holy Spirit. He has promised us that he will return from heaven to receive us. Let''s wait for his return. Our Samaritan is faithful and we have the privilege to live with him eternally.', 'A reflective new year message based on the parable of the Good Samaritan, exploring Jesus as our compassionate savior and the call to active faith beyond ritualistic religion.', '2026-01-01', 6, TRUE, 'en');

-- Insert article images for the new article
INSERT INTO article_images (article_id, url, alt, caption) VALUES
('we-have-a-samaritan', 'assets/images/articles/we-have-a-samaritan.jpg', 'Illustration of the Good Samaritan helping the wounded man', 'We have a Samaritan');

-- Insert article tags for the new article
INSERT INTO article_tags (article_id, tag) VALUES
('we-have-a-samaritan', 'Samaritan'),
('we-have-a-samaritan', 'Jesus'),
('we-have-a-samaritan', 'Salvation'),
('we-have-a-samaritan', 'Faith');
